name: ci-test
on: [push, pull_request, workflow_dispatch]

jobs:

  ps-tree-ci:
    strategy:
      fail-fast: false
      matrix:
        node: [22]
        os: [windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - run: npm run coverage
